=== Hallizar/hallizar.github.io/.astro/collections/ads.schema.json
{
  "$ref": "#/definitions/ads",
  "definitions": {
    "ads": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "slot": {
          "type": "string",
          "enum": [
            "sidebar",
            "in-article",
            "top-header"
          ]
        },
        "imageUrl": {
          "type": "string"
        },
        "targetUrl": {
          "type": "string",
          "format": "uri"
        },
        "active": {
          "type": "boolean",
          "default": true
        },
        "startDate": {
          "type": "string"
        },
        "endDate": {
          "type": "string"
        },
        "priority": {
          "type": "number",
          "default": 1
        },
        "rtbBlockId": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "slot",
        "imageUrl",
        "targetUrl"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Hallizar/hallizar.github.io/src/content/ads/in-article-hosting.json
{
  "priority": 5,
  "active": true,
  "rtbBlockId": "R-A-2849102-3",
  "endDate": "2027-02-28",
  "startDate": "2026-02-01",
  "imageUrl": "https://psv4.vkuserphoto.ru/s/v1/d2/aaKDjnvN7nZcldTAkzqgS6KROCyILAxWCPJ6dTHpQD_EcB6_TKt5OAE-Ws0XZ6Xi1VnvoNDyCA7aK50A2v_gTBcB2hwRo8ohKewylAq-HWtQKvg6qUHL2aOb7xggH7zNQNfNOO_Qx9RQ/ads1.jpg?dl=1",
  "title": "Тут может быть ваша реклама.",
  "id": "fast-edge-cdn-promo",
  "slot": "in-article",
  "targetUrl": "https://hallizar.ru/blog/2026-10-20-%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE"
}

=== Hallizar/hallizar.github.io/src/content/ads/fast-edge-cdn-promo.json
{
  "priority": 1,
  "active": true,
  "endDate": "2027-05-27",
  "startDate": "2026-10-20",
  "imageUrl": "https://psv4.vkuserphoto.ru/s/v1/d2/HeNf3kw5ZS89jE0cDfzRkAZdg_fqzFmc5b6zLcCRzqvSfq9vbCsC5yQhxBwqrh6iwhMMzBX7uCRhpvGVtIcltgiMHtH5CK647ikU0bPpGPIzLY-ba3-XljLRkx8oxK3pr7lKfI_NkYu8/ads4.jpg",
  "title": "Тут может быть ваша реклама.",
  "id": "fast-edge-cdn-promo",
  "slot": "in-article",
  "targetUrl": "https://hallizar.ru/blog/2026-10-20-%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE"
}
